#!/usr/bin/env python3
"""从本地 full 文献库生成前端可懒加载的全库轻索引。

输出:
  - data/literature-full-index.js

该产物不包含 abstract、affiliation、grant 等大字段，只用于全库检索入口和
PMID 级展示回链。原始 data/literature-full.json 仍是本地/Hermes 后台底座。
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from datetime import datetime
from pathlib import Path


projectPath = Path(__file__).resolve().parent.parent
dataDir = projectPath / "data"
fullPath = dataDir / "literature-full.json"
recentJsPath = dataDir / "literature-recent.js"
outputPath = dataDir / "literature-full-index.js"


def loadJson(path: Path):
    return json.loads(path.read_text(encoding="utf-8"))


def loadRecentJs(path: Path) -> list[dict]:
    text = path.read_text(encoding="utf-8")
    match = re.search(r"window\.MG_LITERATURE_DATA\s*=\s*(.*);\s*$", text, re.S)
    if not match:
        raise ValueError("无法解析 data/literature-recent.js")
    return json.loads(match.group(1))


def loadArticles(inputPath: Path) -> tuple[list[dict], str, str]:
    """优先读取 full；没有 full 时回退 recent，保证 GitHub Actions 可兜底。"""
    if inputPath.exists():
        payload = loadJson(inputPath)
        articles = payload if isinstance(payload, list) else payload.get("articles") or payload.get("items") or []
        return articles, "full", str(inputPath.relative_to(projectPath))
    if recentJsPath.exists():
        return loadRecentJs(recentJsPath), "recent_fallback", str(recentJsPath.relative_to(projectPath))
    raise FileNotFoundError("需要 data/literature-full.json 或 data/literature-recent.js")


def compactList(values, limit: int | None = None) -> list:
    if not isinstance(values, list):
        return []
    cleaned = [value for value in values if value not in (None, "")]
    return cleaned[:limit] if limit else cleaned


def compactArticle(article: dict) -> dict:
    """保留全库检索和 PMID 回链需要的最小字段。"""
    pmid = str(article.get("pmid") or "").strip()
    return {
        "pmid": pmid,
        "title": article.get("title") or "",
        "journal": article.get("journal") or "",
        "pub_date": article.get("pub_date") or "",
        "entry_date": article.get("entry_date") or "",
        "url": article.get("url") or (f"https://pubmed.ncbi.nlm.nih.gov/{pmid}/" if pmid else ""),
        "doi": article.get("doi") or "",
        "evidence_level": article.get("evidence_level") or "",
        "study_types": compactList(article.get("study_types")),
        "pub_types": compactList(article.get("pub_types")),
        "journal_if": article.get("journal_if"),
        "journal_quartile": article.get("journal_quartile"),
        "china_related": bool(article.get("china_related")),
        "first_authors": compactList(article.get("first_authors") or article.get("authors"), 3),
        "keywords": compactList(article.get("keywords"), 8),
    }


def sortKey(article: dict):
    return article.get("entry_date") or article.get("pub_date") or "", article.get("pmid") or ""


def writeJs(payload: dict, path: Path) -> None:
    js = json.dumps(payload, ensure_ascii=False, separators=(",", ":"))
    header = (
        "/* AUTO-GENERATED by scripts/buildFullLiteratureIndex.py\n"
        f" * 来源: {payload.get('source_file', '')}\n"
        f" * 生成时间: {payload.get('generated_at', '')}\n"
        " * 说明: 全库轻索引，不包含 abstract；用于静态站全库检索和 PMID 回链。\n"
        " * 请勿手动编辑；运行脚本重新生成。\n"
        " */\n"
    )
    path.write_text(header + f"window.MG_LITERATURE_FULL_INDEX = {js};\n", encoding="utf-8")
    print(f"✅ 已生成 {path.relative_to(projectPath)} ({path.stat().st_size // 1024} KB)")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--input", default=str(fullPath), help="输入 full JSON，默认 data/literature-full.json")
    parser.add_argument("--out", default=str(outputPath), help="输出 JS，默认 data/literature-full-index.js")
    args = parser.parse_args()

    inputPath = Path(args.input)
    if not inputPath.is_absolute():
        inputPath = projectPath / inputPath
    outPath = Path(args.out)
    if not outPath.is_absolute():
        outPath = projectPath / outPath

    try:
        articles, sourceMode, sourceFile = loadArticles(inputPath)
        slimItems = [compactArticle(article) for article in articles if article.get("pmid")]
        slimItems.sort(key=sortKey, reverse=True)
        payload = {
            "generated_at": datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
            "source_mode": sourceMode,
            "source_file": sourceFile,
            "item_count": len(slimItems),
            "omitted_fields": ["abstract", "affiliations", "author_affiliations", "grants", "mesh_terms", "chemicals"],
            "items": slimItems,
        }
        writeJs(payload, outPath)
        print(f"   全库轻索引: {len(slimItems):,} 篇 · source_mode={sourceMode}")
        return 0
    except Exception as exc:
        print(f"❌ 全库轻索引生成失败: {exc}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    sys.exit(main())
